# Generated by Django 5.1.1 on 2024-10-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='what_sells',
            field=models.CharField(default='', max_length=100),
        ),
    ]
